version: "3.7"

services:
  game:
    # build: .
    image: benjaminkrueger/kringle-game
    command: /usr/sbin/sshd -D
    container_name: kringle_game

  webssh:
    image : benjaminkrueger/wetty
    command: wetty -p 3000 --ssh-host game
    ports:
      - 3000:3000
    container_name: kringle_webssh
    
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    container_name: kringle_database
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local
